### PR TITLE
README update, beta is no longer relevant

### PR DESCRIPTION
**Pull request by AerialX**
Documents the new environment variables and updates wording to no longer mention the beta.

### CODE REVIEW

**Comment by jeffheifetz** [comment]
We should also update the gh-pages branch

**Comment by HawkinH** [comment]
For the server_tests we can now also use 

`$ npm test`

to run the clientTests in with all default settings (ie bublmock)

**Comment by AerialX** [comment]
> We should also update the gh-pages branch

Mmhm, I figured the feedback could go here first, then we'd copy that over to the site when done. Though I'm thinking of just making it redirect to the repo at this point. It was only really a separate page before because the beta firmware was a thing.

> npm test

Is this new in the current npm PR? It doesn't seem to work on my end.

**Comment by HawkinH** [comment]
yeah I updated the package.json in the npm PR

**Comment by AerialX** [comment]
Then if this merges first maybe you'll get to learn how to merge/rebase a PR!

**Comment by HawkinH** [comment]
like squashing? but pick and chose?

**Comment by AerialX** [comment]
Sort of. You branched off of master, but if master gets changes since you created your branch... A rebase would take your commits (ones that don't exist in master) and plop them on top of master, so your branch gets all of the latest changes. You could then include the readme change in your PR.

**Comment by jeffheifetz** [comment]
All right, lets merge it then, and deal with gh-pages later

**Pull request merged**
