### PR TITLE
Initial work with the updated Standards

### PR DESCRIPTION
**Pull request by jeffheifetz**

### CODE REVIEW

**Comment by AerialX** [comment]
@jeffheifetz looks like the `extend` needs to mention the whole module name, with the `@bubltechnology` prefix, but I'll assume you're working on that with the shadowing fixes. Please also rebase onto master when you push, we've merged another PR tonight.

**Comment by AerialX** [comment]
> SyntaxError: Use of const in strict mode

node.js in Circle CI is too old to run eslint? We should probably move on to travis anyway.

**Comment by HawkinH** [comment]
ESLint doesn't spit out anything if everything passed right?

**Comment by AerialX** [comment]
That should be how it works, yes. What's the status of this?

**Comment by jeffheifetz** [comment]
@AerialX I think this is ready to go, but if we want to go through the tests further or do more auto-formatting thats OK too

**Comment by AerialX** [comment]
Anything more can be a separate PR, I'm happy with this.

**Pull request merged**
